// SPDX-FileCopyrightText: 2022 metalgearsloth
// SPDX-FileCopyrightText: 2022 wrexbe
// SPDX-FileCopyrightText: 2025 Onezero0
// SPDX-FileCopyrightText: 2025 significant harassment
// SPDX-FileCopyrightText: 2025 sleepyyapril
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.Computer;
using Content.Client.UserInterface.Controls;
using Content.Shared.Shuttles.BUIStates;
using Content.Shared.Shuttles.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class IFFConsoleWindow : FancyWindow,
    IComputerWindow<IFFConsoleBoundUserInterfaceState>
{
    private readonly ButtonGroup _showIFFButtonGroup = new();
    private readonly ButtonGroup _showVesselButtonGroup = new();
    private readonly ButtonGroup _obscureIFFButtonGroup = new(); // _Mono

    public event Action<bool>? ShowIFF;
    public event Action<bool>? ShowVessel;
    public event Action<bool>? ObscureIFF; // _Mono

    public IFFConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        ShowIFFOffButton.Group = _showIFFButtonGroup;
        ShowIFFOnButton.Group = _showIFFButtonGroup;
        ShowIFFOnButton.OnPressed += args => ShowIFFPressed(true);
        ShowIFFOffButton.OnPressed += args => ShowIFFPressed(false);

        ShowVesselOffButton.Group = _showVesselButtonGroup;
        ShowVesselOnButton.Group = _showVesselButtonGroup;
        ShowVesselOnButton.OnPressed += args => ShowVesselPressed(true);
        ShowVesselOffButton.OnPressed += args => ShowVesselPressed(false);

        // _Mono: Obscure button groups & OnPressed(s)
        ObscureIFFOffButton.Group = _obscureIFFButtonGroup;
        ObscureIFFOnButton.Group = _obscureIFFButtonGroup;
        ObscureIFFOnButton.OnPressed += args => ObscureIFFPressed(true);
        ObscureIFFOffButton.OnPressed += args => ObscureIFFPressed(false);
        // End mono
    }

    private void ShowIFFPressed(bool pressed)
    {
        ShowIFF?.Invoke(pressed);
    }

    private void ShowVesselPressed(bool pressed)
    {
        ShowVessel?.Invoke(pressed);
    }

    // _Mono: Obscure IFF invoke
    private void ObscureIFFPressed(bool pressed)
    {
        ObscureIFF?.Invoke(pressed);
    }
    // End mono

    public void UpdateState(IFFConsoleBoundUserInterfaceState state)
    {
        if ((state.AllowedFlags & IFFFlags.HideLabel) != 0x0)
        {
            ShowIFFOffButton.Disabled = false;
            ShowIFFOnButton.Disabled = false;

            if ((state.Flags & IFFFlags.HideLabel) != 0x0)
            {
                ShowIFFOffButton.Pressed = true;
            }
            else
            {
                ShowIFFOnButton.Pressed = true;
            }
        }
        else
        {
            ShowIFFOffButton.Disabled = true;
            ShowIFFOnButton.Disabled = true;
        }

        if ((state.AllowedFlags & IFFFlags.Hide) != 0x0)
        {
            ShowVesselOffButton.Disabled = false;
            ShowVesselOnButton.Disabled = false;

            if ((state.Flags & IFFFlags.Hide) != 0x0)
            {
                ShowVesselOffButton.Pressed = true;
            }
            else
            {
                ShowVesselOnButton.Pressed = true;
            }
        }
        else
        {
            ShowVesselOffButton.Disabled = true;
            ShowVesselOnButton.Disabled = true;
        }

        // _Mono: Button state control for ObscureIFF
        if ((state.AllowedFlags & IFFFlags.ObscureIFF) != 0x0)
        {
            ObscureIFFOffButton.Disabled = false;
            ObscureIFFOnButton.Disabled = false;

            if ((state.Flags & IFFFlags.ObscureIFF) != 0x0)
            {
                ObscureIFFOffButton.Pressed = true;
            }
            else
            {
                ObscureIFFOnButton.Pressed = true;
            }
        }
        else
        {
            ObscureIFFOffButton.Disabled = true;
            ObscureIFFOnButton.Disabled = true;
        }
        // End mono
    }
}
